# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MyRoutineViewer' do
pod 'AVOSCloud'
pod 'FSImageViewer','~>3.2'
end

target 'MyRoutineViewerTests' do

end

